// SW Wrapper: per-selectable-weights-region weight set selection controller.
//
// Sits in the static region around a "selectable_weights" NodeContainer (NC).
// Extracts the weight set index from tUSER on the first beat of each frame and
// forwards it to the NC's s_axis_tap (set selection stream) before admitting
// the frame data.  Uses the same S_CHECK_TUSER convention as dfx_wrapper: the
// tUSER bits on the FIRST beat of a frame specify which weight set to use for
// that frame, so reconfiguration-like decisions can be made before any data
// enters the NC pipeline.
//
// Unlike dfx_wrapper, no DFX Controller, decoupler, or pipeline flushing is
// involved: weight set selection is synchronised implicitly via AXI-Stream
// handshaking.  The wrapper simply holds back input until the set selection
// token has been accepted by the NC's stream tap, then lets the frame through.
//
// Port naming:
//   s_axis_*       : input from upstream (carries tUSER and tLast, generated
//                    by the preceding dfx_tuser_passthrough, dfx_wrapper, or
//                    another sw_wrapper)
//   m_axis_*       : output to downstream (tLast regenerated via beat counter;
//                    tUSER forwarded from hold register)
//   rp_m_axis_*    : output to NC data input (no tUSER needed by FINN ops)
//   rp_s_axis_*    : input from NC data output (no tLast generated by FINN ops)
//   m_axis_setsel_*: set selection stream to NC s_axis_tap (one token per frame)
//
// State machine:
//   S_CHECK_TUSER : peek at first beat (tready=0). On tvalid, latch tUSER
//                   and the set ID → S_SEND_SETSEL.
//   S_SEND_SETSEL : assert m_axis_setsel_tvalid; block input (tready=0). When
//                   the NC's stream-tap accepts the token → S_PASS.
//   S_PASS        : forward frame data to NC. On consumed tLast → S_CHECK_TUSER.
//
// Output tLast generation:
//   The NC (FINN ops) does not generate tLast on its output.  An independent
//   beat counter asserts m_axis_tlast every NUM_OUTPUT_BEATS accepted output
//   beats so that downstream wrappers receive proper frame boundaries.

`timescale 1ns/1ps
module sw_wrapper #(
    parameter int DATA_IN_WIDTH    = 64,  // input AXI-Stream tdata width (bits)
    parameter int DATA_OUT_WIDTH   = 64,  // output AXI-Stream tdata width (bits)
    parameter int TUSER_WIDTH      = 2,   // tUSER width (bits); set ID is low bits
    parameter int NUM_SETS         = 2,   // number of weight sets (= NC bodies)
    parameter int NUM_OUTPUT_BEATS = 1,   // AXI-Stream beats per output frame
    parameter int SETSEL_WIDTH     = 32   // set selection stream width (matches s_axis_tap)
) (
    input  logic                        aclk,
    input  logic                        aresetn,

    // External input (from upstream wrapper; carries tUSER and tLast)
    input  logic [DATA_IN_WIDTH-1:0]    s_axis_tdata,
    input  logic                        s_axis_tvalid,
    output logic                        s_axis_tready,
    input  logic                        s_axis_tlast,
    input  logic [TUSER_WIDTH-1:0]      s_axis_tuser,

    // External output (to downstream; tLast regenerated, tUSER forwarded)
    output logic [DATA_OUT_WIDTH-1:0]   m_axis_tdata,
    output logic                        m_axis_tvalid,
    input  logic                        m_axis_tready,
    output logic                        m_axis_tlast,
    output logic [TUSER_WIDTH-1:0]      m_axis_tuser,

    // To NC data input (no tUSER needed; tLast forwarded for protocol compliance)
    output logic [DATA_IN_WIDTH-1:0]    rp_m_axis_tdata,
    output logic                        rp_m_axis_tvalid,
    input  logic                        rp_m_axis_tready,
    output logic                        rp_m_axis_tlast,

    // From NC data output (no tUSER; no tLast generated by NC FINN ops)
    input  logic [DATA_OUT_WIDTH-1:0]   rp_s_axis_tdata,
    input  logic                        rp_s_axis_tvalid,
    output logic                        rp_s_axis_tready,
    input  logic                        rp_s_axis_tlast,  // present for interface compliance, unused

    // Set selection stream to NC s_axis_tap (one token per frame)
    output logic [SETSEL_WIDTH-1:0]     m_axis_setsel_tdata,
    output logic                        m_axis_setsel_tvalid,
    input  logic                        m_axis_setsel_tready
);

    localparam int SET_ID_W  = (NUM_SETS > 1) ? $clog2(NUM_SETS) : 1;
    localparam int OUT_CNT_W = (NUM_OUTPUT_BEATS > 1) ? $clog2(NUM_OUTPUT_BEATS) : 1;

    typedef enum logic [1:0] {
        S_CHECK_TUSER = 2'd0,
        S_SEND_SETSEL = 2'd1,
        S_PASS        = 2'd2
    } state_t;

    state_t                  state;
    logic [TUSER_WIDTH-1:0]  tuser_reg;    // full tUSER of the current frame
    logic [OUT_CNT_W-1:0]    out_beat_cnt; // counts accepted output beats for tLast

    // --------------------------------------------------------------------------
    // Input path: only active in S_PASS; all other states block input (tready=0)
    // --------------------------------------------------------------------------
    logic input_active;
    assign input_active = (state == S_PASS);

    assign rp_m_axis_tdata  = s_axis_tdata;
    assign rp_m_axis_tvalid = s_axis_tvalid & input_active;
    assign rp_m_axis_tlast  = s_axis_tlast;
    assign s_axis_tready    = rp_m_axis_tready & input_active;

    // --------------------------------------------------------------------------
    // Output path: always forwarded; tLast regenerated by beat counter;
    // tUSER restored from hold register so downstream wrappers see it.
    // --------------------------------------------------------------------------
    logic out_beat_last;
    assign out_beat_last = (out_beat_cnt == OUT_CNT_W'(NUM_OUTPUT_BEATS - 1));

    assign m_axis_tdata     = rp_s_axis_tdata;
    assign m_axis_tvalid    = rp_s_axis_tvalid;
    assign m_axis_tlast     = out_beat_last;
    assign m_axis_tuser     = tuser_reg;
    assign rp_s_axis_tready = m_axis_tready;

    // --------------------------------------------------------------------------
    // Set selection stream: only valid in S_SEND_SETSEL.
    // tdata carries the set index from tUSER, zero-extended to SETSEL_WIDTH bits.
    // --------------------------------------------------------------------------
    assign m_axis_setsel_tdata  = SETSEL_WIDTH'(tuser_reg[SET_ID_W-1:0]);
    assign m_axis_setsel_tvalid = (state == S_SEND_SETSEL);

    // --------------------------------------------------------------------------
    // Output beat counter (independent of FSM; tracks output frame boundaries)
    // --------------------------------------------------------------------------
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn)
            out_beat_cnt <= '0;
        else if (rp_s_axis_tvalid & m_axis_tready)
            out_beat_cnt <= out_beat_last ? '0 : out_beat_cnt + 1'b1;
    end

    // --------------------------------------------------------------------------
    // FSM
    // --------------------------------------------------------------------------
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            state     <= S_CHECK_TUSER;
            tuser_reg <= '0;
        end else begin
            case (state)
                // ------------------------------------------------------------------
                // Peek at the first beat of the next frame without consuming it
                // (tready=0 because input_active=0 here). When the upstream master
                // presents tvalid, latch the full tUSER vector (including the set
                // ID in the low bits) and advance to send the selection token.
                // ------------------------------------------------------------------
                S_CHECK_TUSER: begin
                    if (s_axis_tvalid) begin
                        tuser_reg <= s_axis_tuser;
                        state     <= S_SEND_SETSEL;
                    end
                end

                // ------------------------------------------------------------------
                // Hold input blocked (tready=0) while asserting the set selection
                // stream.  The NC's stream tap must accept the token before frame
                // data is admitted, ensuring the correct weight set is loaded.
                // ------------------------------------------------------------------
                S_SEND_SETSEL: begin
                    if (m_axis_setsel_tready)
                        state <= S_PASS;
                end

                // ------------------------------------------------------------------
                // Forward input beats to the NC.  On the consumed tLast (end of
                // frame), return to S_CHECK_TUSER to sample the next frame's tUSER.
                // ------------------------------------------------------------------
                S_PASS: begin
                    if (s_axis_tvalid & s_axis_tready & s_axis_tlast)
                        state <= S_CHECK_TUSER;
                end

                default: state <= S_CHECK_TUSER;
            endcase
        end
    end

endmodule
