include: ci/.gitlab-setup.yml

stages:
  - sync
  - build
  - test

variables:
  PIPELINE_NAME:
    description: "Optional name to better identify this pipeline"
    value: ""
  TEST_SUITE:
    description: "Select test suite to run"
    value: "full_ci"
    options:
      - "none"
      - "quicktest_ci"
      - "full_ci"
  CPU_CORES:
    description: "Select number of CPU cores and test workers"
    value: "32"
  CPU_CORES_BENCH:
    description: "Select number of CPU cores for benchmark runs"
    value: "32"
  MEM_BENCH:
    description: "Select memory for each benchmark job"
    value: "128G"
  PARALLEL_JOBS:
    description: "Number of parallel Slurm array jobs per Benchmark job"
    value: "1"
  SLURM_TIMEOUT:
    description: "Select SLURM timeout"
    value: "1-0" # [days-hours]
  SLURM_PARTITION:
    description: "Slurm partition (e.g., normal, largemem, fpga, gpu)"
    value: "normal"
  SLURM_QOS:
    description: "Optional --exclusive or QoS option (include --qos, e.g., --qos express)"
    value: ""
  MANUAL_CFG_PATH:
    description: "Name (in ci/cfg/) or path (relative to LOCAL_CFG_DIR) of benchmarking config to run"
    value: ""

workflow:
  name: '$PIPELINE_NAME'
  rules:
    # Run pipeline for GitHub PRs to dev (does not support PRs from forks)
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" && $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "dev"
    # Run pipeline for pushes to dev or main
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"
    # Run pipeline if manually triggered via API or web GUI
    - if: $CI_PIPELINE_SOURCE == "api"
    - if: $CI_PIPELINE_SOURCE == "web"
    # Run pipeline if scheduled (only for nightly sync of finn-dev)
    - if: $CI_PIPELINE_SOURCE == "schedule"

Sync finn-dev:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: sync
  tags:
    # Run where full Docker + Singularity is available
    - image_build
  rules:
    # Only run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - mkdir -p ../github_clone && cd ../github_clone
    - rm -rf finn-plus # Ensure we do a fresh clone (TODO: better way to handle this on job level?)
    - git clone git@github.com:eki-project/finn-plus.git && cd finn-plus
    - git remote add upstream https://github.com/Xilinx/finn.git
    - git checkout finn-dev
    - git pull upstream dev
    - git push origin finn-dev

Build:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: build
  tags:
    - otus_login
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    # Otherwise run
    - when: always
  before_script:
    - !reference [.n2_setup_general, before_script]
    - !reference [.n2_setup_xilinx_2022_2, before_script]
    # Install current version of Poetry
    - python3 -m venv poetry-install
    - poetry-install/bin/pip install poetry
    - shopt -s expand_aliases
    - alias poetry=poetry-install/bin/poetry
  script:
    # Let Poetry create virtual environment (.venv) and install Python dependencies
    # TODO: is it possible to cache the entire venv for the following jobs?
    - poetry install
    - export POETRY_VIRTUALENVS_CREATE=false #DO NOT TOUCH: needed to build sub-packages
    # Also build .whl finn-plus-tests package (for test dependencies)
    - poetry build -P tests --clean --format=wheel
    # Also build .whl finn-plus-notebooks package (for notebooks dependencies)
    - poetry build -P notebooks --format=wheel
    # Set the version of the sub-packages in the main pyproject.toml
    - |
      VERSION=$(poetry version -s -C tests)
      # Update main pyproject.toml with the correct version
      sed -i "s/finn-plus-tests = { version = \"\*\", optional = true }/finn-plus-tests = { version = \"$VERSION\", optional = true }/" pyproject.toml
      sed -i "s/finn-plus-notebooks = { version = \"\*\", optional = true }/finn-plus-notebooks = { version = \"$VERSION\", optional = true }/" pyproject.toml
    - export POETRY_VIRTUALENVS_CREATE=true #DO NOT TOUCH: revert to default behavior
    # Build .whl finn-plus package
    - poetry build --clean --format=wheel
    # Let FINN download additional dependencies, cache resulting deps directory
    # Also fetch & checkout DVC-managed data, $CI_DVC_CACHE_DIR persists between jobs
    - |
      source .venv/bin/activate
      finn deps update --dependency-path ./deps --accept-defaults
      dvc config cache.dir $CI_DVC_CACHE_DIR
      dvc pull
  artifacts:
    name: "finn-plus_package"
    paths:
      - dist/*.whl
      - tests/dist/*.whl
      - notebooks/dist/*.whl
    expire_in: 1 week
  cache:
    key: $CI_COMMIT_SHA #TODO: cache based on relevant files
    paths:
      - deps

FINN Test Suite 2022.2:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: test
  tags:
    - otus
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    # Do not run if test suite has been deselected
    - if: $TEST_SUITE == "none"
      when: never
    # Do not run for PRs to dev (run only for pushes)
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" && $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "dev"
      when: never
    # Always run, as long as there was no prior failure
    - when: on_success
  cache:
    key: $CI_COMMIT_SHA
    policy: pull
    paths:
      - deps
  variables:
    SCHEDULER_PARAMETERS: "-A $PROJECT_ACCOUNT -p $SLURM_PARTITION -t $SLURM_TIMEOUT $SLURM_QOS --nodes 1 --ntasks 1 --cpus-per-task $CPU_CORES --exclusive"
    PYTEST_PARALLEL: "$CPU_CORES"
  extends: .setup_full_2022_2
  script:
    # Launch additional monitoring
    - $JOB_MONITORING_DIR/monitor.sh $JOB_MONITORING_DIR/$CI_PIPELINE_ID/$HOSTNAME.log &
    # Launch FINN via test command, includes preparation of (cached) dependencies
    # Also fetch & checkout DVC-managed data, which should already be cached in $CI_DVC_CACHE_DIR
    - |
      source finn-plus-venv/bin/activate
      dvc config cache.dir $CI_DVC_CACHE_DIR
      dvc pull
      finn test --variant $TEST_SUITE --dependency-path ./deps --build-path $FINN_BUILD_DIR --num-default-workers 1 --num-test-workers $PYTEST_PARALLEL
  artifacts:
    name: "test_reports"
    when: always
    paths:
      - reports/
    reports:
      junit: reports/*.xml

FINN Test Suite 2024.2:
  extends:
    - FINN Test Suite 2022.2
    - .setup_full_2024_2
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    # Do not run if test suite has been deselected
    - if: $TEST_SUITE == "none"
      when: never
    # Always run, as long as there was no prior failure
    - when: on_success

Bench (Manual):
  stage: test
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $MANUAL_CFG_PATH != ""
  trigger:
    include: ci/.gitlab-bench.yml
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    BENCH_CFG: "manual"

Bench (Basic):
  stage: test
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $MANUAL_CFG_PATH == ""
  trigger:
    include: ci/.gitlab-bench.yml
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  parallel:
    matrix:
      - BENCH_CFG: [regression_basic]

Bench (Extended):
  stage: test
  rules:
    # Do not run on a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    # Do not run for PRs to dev (run only for pushes)
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" && $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "dev"
      when: never
    - if: $MANUAL_CFG_PATH == ""
  trigger:
    include: ci/.gitlab-bench.yml
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    PARALLEL_JOBS: "8"
  parallel:
    matrix:
      - BENCH_CFG: [regression_extended, regression_transformer, microbenchmark_basic]
