from collections.abc import Iterator

class Kernel:
    def __init__(self, name: str) -> None: ...

class Port:
    def name(self) -> str: ...
    def dir(self) -> int: ...
    def width(self) -> int: ...
    def isInput(self) -> bool: ...  # noqa: N802
    def isOutput(self) -> bool: ...  # noqa: N802
    def isInout(self) -> bool: ...  # noqa: N802
    def read(self) -> Port: ...
    def write_back(self) -> None: ...
    def hasUnknown(self) -> bool: ...  # noqa: N802
    def isZero(self) -> bool: ...  # noqa: N802
    def as_bool(self) -> bool: ...
    def as_unsigned(self) -> int: ...
    def as_binstr(self) -> str: ...
    def as_hexstr(self) -> str: ...
    def clear(self) -> Port: ...
    def set(self, value: int) -> Port: ...
    def set_binstr(self, value: str) -> Port: ...
    def set_hexstr(self, value: str) -> Port: ...

class Design:
    def __init__(
        self, kernel: Kernel, design_lib: str, log_file: str | None, wdb_file: str | None
    ) -> None: ...
    def trace_all(self) -> None: ...
    def run(self, cycles: int) -> None: ...
    def restart(self) -> None: ...
    def get_status(self) -> int: ...
    def get_error_info(self) -> str: ...
    def num_ports(self) -> int: ...
    def getPort(self, name: str) -> Port: ...  # noqa: N802
    def ports(self) -> Iterator[Port]: ...
