# This file defines some basic scripts used to setup the FINN environment on the runner

.n2_setup_general:
  before_script:
    - ml lang/Python/3.10.4-GCCcore-11.3.0
    - ml tools/git-lfs/3.6.1
    - ml tools/UnZip/6.0-GCCcore-11.3.0
    - ml devel/ncurses/5.9
    - ulimit -s unlimited # Increase stack size limit

.n2_setup_xilinx_2022_2:
  before_script:
    - module load fpga
    - module load xilinx/xrt/2.14 # includes Vitis/Vivado 2022.2
    - ml fpga/xilinx/vitis_hls_xcd_fix
    - export PLATFORM_PATH=$FINN_CUSTOM_PLATFORM_PATH # override with custom platform path
    # module load will set PLATFORM_REPO_PATHS to one specific platform, revert to top-level PLATFORM_PATH
    - export PLATFORM_REPO_PATHS=$PLATFORM_PATH
    # Workaround for https://github.com/eki-project/finn-plus/issues/112
    - export LD_LIBRARY_PATH=$XILINX_VIVADO/lib/lnx64.o:$XILINX_VITIS/lnx64/tools/fpo_v7_1:$LD_LIBRARY_PATH
    # Force use of system SSL libraries on Otus
    - export LD_PRELOAD=/lib64/libssl.so.3:/lib64/libcrypto.so.3:$LD_PRELOAD

.n2_setup_xilinx_2024_2:
  before_script:
    - module load fpga
    - ml xilinx/xrt/2.16_static_boost_1.75 # includes Vitis/Vivado 2023.2
    - module swap xilinx/vitis/24.2 # switch to Vitis/Vivado 2024.2
    - ml fpga/xilinx/vitis_hls_xcd_fix
    - export PLATFORM_PATH=$FINN_CUSTOM_PLATFORM_PATH # override with custom platform path
    # module load will set PLATFORM_REPO_PATHS to one specific platform, revert to top-level PLATFORM_PATH
    - export PLATFORM_REPO_PATHS=$PLATFORM_PATH
    # Workaround for https://github.com/eki-project/finn-plus/issues/112
    - export LD_LIBRARY_PATH=$XILINX_VIVADO/lib/lnx64.o:$XILINX_VITIS/lnx64/tools/fpo_v7_1:$LD_LIBRARY_PATH
    # Force use of system SSL libraries on Otus
    - export LD_PRELOAD=/lib64/libssl.so.3:/lib64/libcrypto.so.3:$LD_PRELOAD

.setup_venv_from_whl:
  before_script:
    # Move everything to working directory (e.g., RAMdisk)
    - cp -dfR . $PATH_WORKDIR
    - cd $PATH_WORKDIR
    # Create fresh virtual environment and install finn-plus from .whl (artifact)
    - python3 -m venv finn-plus-venv
    - finn-plus-venv/bin/pip install 'torch~=2.7.1' 'torchvision~=0.22.1' --extra-index-url https://download.pytorch.org/whl/cu121
    - finn-plus-venv/bin/pip install 'dvc[webdav]~=3.66.0' 'dvclive[image]~=3.49.0'
    - finn-plus-venv/bin/pip install tests/dist/*.whl
    - finn-plus-venv/bin/pip install notebooks/dist/*.whl
    - finn-plus-venv/bin/pip install dist/*.whl
    # Install dataset loading for some end to end tests. Usually only needed to run pynq driver.
    - finn-plus-venv/bin/pip install finn-dataset-loading

.setup_full_2022_2:
  before_script:
    - !reference [.n2_setup_general, before_script]
    - !reference [.n2_setup_xilinx_2022_2, before_script]
    - !reference [.setup_venv_from_whl, before_script]

.setup_full_2024_2:
  before_script:
    - !reference [.n2_setup_general, before_script]
    - !reference [.n2_setup_xilinx_2024_2, before_script]
    - !reference [.setup_venv_from_whl, before_script]
