# Copyright (C) 2020, Xilinx, Inc.
# Copyright (C) 2024, Advanced Micro Devices, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of FINN nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""Transformations for inserting and setting the size of FIFOs in FINN dataflow graphs."""

import json
from onnx import TensorProto, helper
from pathlib import Path
from qonnx.core.datatype import DataType
from qonnx.core.modelwrapper import ModelWrapper
from qonnx.transformation.base import Transformation
from qonnx.transformation.general import GiveReadableTensorNames, SortGraph
from typing import Literal, TypeAlias, cast

from finn.util.basic import getHWCustomOp
from finn.util.exception import FINNUserError
from finn.util.logging import log

from onnx import NodeProto


from qonnx.custom_op.registry import getCustomOp
from qonnx.transformation.general import GiveUniqueNodeNames

from finn.builder.build_dataflow_config import DataflowBuildConfig
from finn.transformation.fpgadataflow.insert_fifo import InsertFIFO
from finn.transformation.fpgadataflow.specialize_layers import SpecializeLayers
from finn.util.exception import FINNInternalError

FIFODepthConfig: TypeAlias = list[dict[str, list[int]]]


class ApplyFIFODepthsFromFile(Transformation):
    """Apply FIFO depths from a JSON file generated by a previous run of build_dataflow
    with auto_fifo_depths enabled."""

    def __init__(self, fifo_config_file: Path) -> None:
        """Initialize ApplyFIFODepthsFromFile with the path to the FIFO configuration file."""
        super().__init__()
        self.fifo_config_file = fifo_config_file

    def apply(self, model: ModelWrapper) -> tuple[ModelWrapper, bool]:
        """Apply FIFO depths from the configuration file to the model."""
        with self.fifo_config_file.open() as f:
            fifo_info = json.load(f)

        # JSON file format:
        # {
        # "fifo_depths": {
        #     "StreamingFIFO_rtl_0": 2,
        # },
        # "fifo_sizes": {
        #     "StreamingFIFO_rtl_0": 64,
        # },
        # "impl_style": {
        #     "StreamingFIFO_rtl_0": "rtl",
        # },
        # "ram_style": {
        #     "StreamingFIFO_rtl_0": "block",
        # },
        # "total_fifo_size_kiB": 31
        # }
        fifo_nodes = model.get_nodes_by_op_type("StreamingFIFO_rtl")

        if len(fifo_nodes) != len(fifo_info["fifo_depths"]):
            raise FINNUserError(
                f"Number of FIFO nodes in the model ({len(fifo_nodes)}) does not match the number "
                f"of FIFO nodes in the configuration file ({len(fifo_info['fifo_depths'])})"
            )
        graph_modified = False
        for node in fifo_nodes:
            if node.name not in fifo_info["fifo_depths"]:
                raise FINNUserError(f"FIFO node {node.name} not found in configuration file")
            n_inst = getHWCustomOp(node)
            depth = fifo_info["fifo_depths"][node.name]
            old_depth = n_inst.get_nodeattr("depth")
            if depth == old_depth:
                continue
            impl_style = fifo_info["impl_style"][node.name]
            ram_style = fifo_info["ram_style"][node.name]
            n_inst.set_nodeattr("depth", depth)
            n_inst.set_nodeattr("impl_style", impl_style)
            n_inst.set_nodeattr("ram_style", ram_style)

            producer = model.find_producer(node.input[0])
            if producer is not None:
                prod_node = getHWCustomOp(producer)
                out_fifo_depths = cast("list[int]", prod_node.get_nodeattr("outFIFODepths"))
                succ = cast("list[NodeProto]", model.find_direct_successors(producer))
                num_succ = len(succ)
                if len(out_fifo_depths) != num_succ:
                    out_fifo_depths = [0] * num_succ
                for i, s in enumerate(succ):
                    if s.name == node.name:
                        out_fifo_depths[i] = depth
                prod_node.set_nodeattr(
                    "outFIFODepths", cast("list[int|str|float]", out_fifo_depths)
                )

            graph_modified = True
        return (model, graph_modified)


def get_fifo_split_configs(
    depth: int, max_qsrl_depth: int = 256, max_vivado_depth: int = 32768
) -> list[tuple[int, str]]:
    """Break non-power-of-2 sized FIFO depths into several ones."""

    def floor_pow2(x: int) -> int:
        """Return the largest power of 2 less than or equal to x."""
        if (x & (x - 1) == 0) and x != 0:
            return x
        return 1 << ((x - 1).bit_length() - 1)

    def decompose_pow2(x: int) -> list[int]:
        """Decompose x into a sum of powers of 2,
        with each power of 2 no larger than max_qsrl_depth.
        """
        if x <= max_qsrl_depth:
            return [x]
        r = floor_pow2(x)
        if x == r:
            return [x]
        return [r, *decompose_pow2(x - r)]

    ret = []
    # trivial case: for small FIFOs, return as-is with rtl style
    if depth <= max_qsrl_depth:
        return [(depth, "rtl")]
    # first pass: ensure max depth is respected
    # (restricted by Vivado AXIS infra IP)
    remainder = depth
    while remainder != 0:
        if remainder > max_vivado_depth:
            ret.append(max_vivado_depth)
            remainder -= max_vivado_depth
        else:
            ret.append(remainder)
            remainder = 0
    # second pass: break non-power-of-2 sized FIFOs
    # into several ones

    ret_pass2 = list(map(decompose_pow2, ret))
    # unpack list of lists
    ret_pass2 = [x for dec_list in ret_pass2 for x in dec_list]

    # finally, add impl_style to each split FIFO
    ret_final = []
    for cand_depth in ret_pass2:
        if cand_depth <= max_qsrl_depth:
            ret_final.append((max(2, cand_depth), "rtl"))
        else:
            ret_final.append((cand_depth, "vivado"))

    return ret_final


class SplitLargeFIFOs(Transformation):
    """Split large FIFOs before implementation, for two reasons.

    - impl_style="vivado" supports a max depth of 32k. Any larger
      FIFOs must be implemented as a sequence of smaller FIFOs.
    - impl_style="vivado" requires power-of-two depths, which is
      normally handled by rounding up to the nearest power-of-two.
      So a FIFO of size 8196 normally gets rounded-up to a depth of
      16384 and wastes a lot of resources. Here, instead, we split
      this up into two FIFOs of depth 8192 + 4.

    """

    def __init__(self, max_qsrl_depth: int = 256, max_vivado_depth: int = 32768) -> None:
        """Initialize SplitLargeFIFOs with maximum FIFO depth constraints."""
        super().__init__()
        self.max_qsrl_depth = max_qsrl_depth
        self.max_vivado_depth = max_vivado_depth

    def apply(self, model: ModelWrapper) -> tuple[ModelWrapper, Literal[False]]:
        """Split large FIFOs into chains of smaller power-of-two FIFOs."""
        graph = model.graph
        graph_modified = False
        for node_ind, node in enumerate(graph.node, 1):
            if node.op_type == ("StreamingFIFO_rtl"):
                n_inst = getHWCustomOp(node)
                depth = cast("int", n_inst.get_nodeattr("depth"))
                cfgs = get_fifo_split_configs(depth, self.max_qsrl_depth, self.max_vivado_depth)
                if len(cfgs) > 1:
                    fld_shape = n_inst.get_folded_output_shape()
                    n_shape = n_inst.get_normal_output_shape()
                    dtype = cast("str", n_inst.get_nodeattr("dataType"))
                    ram_style = n_inst.get_nodeattr("ram_style")
                    shape = model.get_tensor_shape(node.input[0])
                    log.info(
                        f"Splitting FIFO {node.name} of depth {depth} "
                        f"into {len(cfgs)} FIFOs with depths {[c[0] for c in cfgs]}"
                    )
                    for i, (fifo_depth, impl_style) in enumerate(cfgs):
                        inp = node.input[0] if i == 0 else node.name + "_" + str(i - 1) + "_out"
                        if i == len(cfgs) - 1:
                            outp = node.output[0]
                        else:
                            outp = node.name + "_" + str(i) + "_out"
                            out_tensor = helper.make_tensor_value_info(
                                outp, TensorProto.FLOAT, shape
                            )
                            graph.value_info.append(out_tensor)
                            model.set_tensor_datatype(out_tensor.name, DataType[dtype])
                        fifo_node = helper.make_node(
                            "StreamingFIFO_rtl",
                            [inp],
                            [outp],
                            domain="finn.custom_op.fpgadataflow.rtl",
                            backend="fpgadataflow",
                            depth=fifo_depth,
                            folded_shape=fld_shape,
                            normal_shape=n_shape,
                            dataType=dtype,
                            impl_style=impl_style,
                            ram_style=ram_style,
                            name=node.name + "_" + str(i),
                        )
                        graph.node.insert(node_ind + i, fifo_node)

                    graph.node.remove(node)
                    graph_modified = True
        if graph_modified:
            model = model.transform(SortGraph())
            model = model.transform(GiveReadableTensorNames())
        return (model, False)


class ApplySimulatedFIFOSizes(Transformation):
    """Apply a FIFO sizing configuration to the model.
    If FIFOs already exist the step is skipped."""

    def __init__(
        self,
        cfg: DataflowBuildConfig,
        fifo_config: Path | None = None,
        max_qsrl_depth: int = 256,
        vivado_ram_style: str = "block",
    ) -> None:
        """If given read the config json from the given path.
        Otherwise check in the output directory.
        """
        self.cfg = cfg
        self.max_qsrl_depth = max_qsrl_depth
        self.vivado_ram_style = vivado_ram_style
        self.fifo_config = fifo_config

    def apply(self, model: ModelWrapper) -> tuple[ModelWrapper, bool]:
        """Apply FIFO Simulation Depths to the model."""
        if len(list(filter(lambda node: "StreamingFIFO" in node.op_type, model.graph.node))) > 0:
            log.warning(
                "It seems that StreamingFIFOs have already "
                "been inserted into the graph. Skipping insertion of FIFOs."
            )
            return model, False

        if self.fifo_config is None:
            p = model.get_metadata_prop("fifo_data")
            if p == "" or p is None:
                raise FINNInternalError(
                    "FIFO sizing simulation was not run before inserting simulated FIFO sizes!"
                )
            self.path = Path(p)
        else:
            self.path = self.fifo_config

        self.fifo_depths: FIFODepthConfig = []
        with self.path.open() as f:
            self.fifo_depths = cast("FIFODepthConfig", json.load(f))

        if len(model.graph.node) != len(self.fifo_depths):
            raise FINNUserError(
                "There are no StreamingFIFOs in the graph, yet the number "
                "of nodes and number of FIFO sizes differ. There may be "
                "unaccounted for nodes that have not been part of the FIFO "
                "simulation. Consider re-running simulation directly before "
                "applying the FIFO sizes. It might also be that your model "
                "or config is outdated, in which case it is recommended to "
                "re-run the entire flow from start to finish."
            )

        # FIFO sizes are set as the maximum of outFIFODepth and inFIFODepth of the successor node
        # Only set the outFIFODepth, because setting both is redundant as inFIFODepth defaults to 0.
        # Remove all in/outFIFODepths in model for clean slate
        graph = model.graph
        for node in graph.node:
            predecessors = model.find_direct_predecessors(node)
            successors = model.find_direct_successors(node)
            n = getCustomOp(node)
            if n is not None:
                if predecessors is not None:
                    n.set_nodeattr(
                        "inFIFODepths",
                        cast("list[str | int | float]", [0] * len(predecessors)),
                    )
                if successors is not None:
                    n.set_nodeattr(
                        "outFIFODepths",
                        cast("list[str | int | float]", [0] * len(successors)),
                    )

        # Set new outFIFODepths according to config
        graph = model.graph
        node_ind = -1
        for first_node in graph.node:
            node_ind += 1
            n0 = getCustomOp(first_node)
            if n0 is None:
                raise FINNInternalError(
                    f"Node {first_node.name} does not have a custom op instance."
                    " This is required for FIFO insertion."
                )
            if first_node.name != self.fifo_depths[node_ind]["node"]:
                raise FINNInternalError(
                    f"Node name {first_node.name} does not match expected name "
                    f"{self.fifo_depths[node_ind]['node']} at index {node_ind}. "
                    "This may be due to a mismatch between the model and the config, "
                    "or due to changes in the model after the simulation was run. "
                    "Consider re-running the entire flow from start to finish."
                )
            fifos = cast("list[str | int | float]", (self.fifo_depths[node_ind]["depths"]))
            n0.set_nodeattr("outFIFODepths", fifos)

        # Insert the FIFOs into the model
        model = model.transform(InsertFIFO(True, self.max_qsrl_depth, self.vivado_ram_style))

        model = model.transform(GiveUniqueNodeNames())
        model = model.transform(GiveReadableTensorNames())
        model = model.transform(SpecializeLayers(self.cfg._resolve_fpga_part()))  # noqa
        model = model.transform(GiveUniqueNodeNames())
        model = model.transform(GiveReadableTensorNames())

        # Sanity check to make sure fifos were inserted
        inserted_fifo_count = sum(
            [int("StreamingFIFO" in node.op_type) for node in model.graph.node]
        )
        if inserted_fifo_count == 0:
            raise FINNInternalError(
                "No FIFOs were inserted. This may be due to "
                "wrong network configuration, step order or "
                "a number of other things."
            )
        if inserted_fifo_count < int(0.4 * float(len(model.graph.node))):
            log.warning(
                "The number of inserted FIFOs makes up less than 40%"
                " of the total number of nodes in the model. This could "
                "point to a potential error."
            )

        return model, False
